# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nets/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nets/config.proto',
  package='nets',
  syntax='proto2',
  serialized_pb=_b('\n\x11nets/config.proto\x12\x04nets\"\r\n\x0bLayerConfig\"\x82\x01\n\rNetworkConfig\x12/\n\x06layers\x18\x01 \x03(\x0b\x32\x1f.nets.NetworkConfig.LayersEntry\x1a@\n\x0bLayersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.nets.LayerConfig:\x02\x38\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LAYERCONFIG = _descriptor.Descriptor(
  name='LayerConfig',
  full_name='nets.LayerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=40,
)


_NETWORKCONFIG_LAYERSENTRY = _descriptor.Descriptor(
  name='LayersEntry',
  full_name='nets.NetworkConfig.LayersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='nets.NetworkConfig.LayersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='nets.NetworkConfig.LayersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=173,
)

_NETWORKCONFIG = _descriptor.Descriptor(
  name='NetworkConfig',
  full_name='nets.NetworkConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='nets.NetworkConfig.layers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NETWORKCONFIG_LAYERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=173,
)

_NETWORKCONFIG_LAYERSENTRY.fields_by_name['value'].message_type = _LAYERCONFIG
_NETWORKCONFIG_LAYERSENTRY.containing_type = _NETWORKCONFIG
_NETWORKCONFIG.fields_by_name['layers'].message_type = _NETWORKCONFIG_LAYERSENTRY
DESCRIPTOR.message_types_by_name['LayerConfig'] = _LAYERCONFIG
DESCRIPTOR.message_types_by_name['NetworkConfig'] = _NETWORKCONFIG

LayerConfig = _reflection.GeneratedProtocolMessageType('LayerConfig', (_message.Message,), dict(
  DESCRIPTOR = _LAYERCONFIG,
  __module__ = 'nets.config_pb2'
  # @@protoc_insertion_point(class_scope:nets.LayerConfig)
  ))
_sym_db.RegisterMessage(LayerConfig)

NetworkConfig = _reflection.GeneratedProtocolMessageType('NetworkConfig', (_message.Message,), dict(

  LayersEntry = _reflection.GeneratedProtocolMessageType('LayersEntry', (_message.Message,), dict(
    DESCRIPTOR = _NETWORKCONFIG_LAYERSENTRY,
    __module__ = 'nets.config_pb2'
    # @@protoc_insertion_point(class_scope:nets.NetworkConfig.LayersEntry)
    ))
  ,
  DESCRIPTOR = _NETWORKCONFIG,
  __module__ = 'nets.config_pb2'
  # @@protoc_insertion_point(class_scope:nets.NetworkConfig)
  ))
_sym_db.RegisterMessage(NetworkConfig)
_sym_db.RegisterMessage(NetworkConfig.LayersEntry)


_NETWORKCONFIG_LAYERSENTRY.has_options = True
_NETWORKCONFIG_LAYERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
